apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-svc
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["default-token-j6hq2", "mysql-secret", test-token-ljwkx]
    verbs: ["list", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-svc-test-binding
  namespace: default
roleRef:
  kind: Role
  name: list-svc
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: test
    namespace: default