apiVersion: v1
kind: Service
metadata:
  name: userdb
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql-userdb
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: userdb
  labels:
    app: mysql-userdb
spec:
  replicas: 1
  serviceName: userdb
  selector:
    matchLabels:
      app: mysql-userdb
  template:
    metadata:
      labels:
        app: mysql-userdb
    spec:
      securityContext:
        fsGroup: 3000
      containers:
      - name: mysql-userdb
        image: mysql:8.0
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 3306
        securityContext:
          privileged: false
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          value: "userdb"
        volumeMounts:
        - name: userdb-persistent-storage
          mountPath: /var/lib/mysql
        - name: userdb-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: 400Mi
            cpu: 300m
          limits:
            memory: 600Mi
            cpu: 600m
      - name: tcpdump
        image: corfr/tcpdump
        imagePullPolicy: Always
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: tcpdump-init
            mountPath: /home/root/
          - name: tcpdump-persistent-storage
            mountPath: /tmp
        command: ["/bin/sh", "-c"]
        args:
        - sh /home/root/start-tcpdump.sh userdb 900
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
      restartPolicy: Always
      initContainers:
      - name: init-userdb
        image: alpine:3
        command: ["/bin/sh", "-c"]
        args:
        - chown -R 999:999 /var/lib/mysql
        volumeMounts:
        - name: userdb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: userdb-persistent-storage
        persistentVolumeClaim:
          claimName: userdb-pv-claim
      - name: userdb-init
        configMap:
          name: userdb-init-config
      - name: tcpdump-init
        configMap:
          name: tcpdump-script-configmap
      - name: tcpdump-persistent-storage
        persistentVolumeClaim:
          claimName: userdb-tcpdump-pvc

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userdb-init-config
data:
  initdb.sql: |
    CREATE TABLE IF NOT EXISTS users
    (
      Username varchar(100) NOT NULL,
      Password varchar (100) NOT NULL,
      CreditCard varchar(100),
      PRIMARY KEY(Username)
    );
  populate.sql: |
    INSERT INTO users VALUES
    (
        "jonestech",
        "$2b$12$pMlvgFC2qXE8ltH1vLdLMO1CA2vANF2hrbmMOOAPxKJXixb3yPzZi",
        "3461-9022-0010-1819"
    );
    INSERT INTO users VALUES
    (
        "cassie123",
        "$2b$12$HXNG3vwtlMeHrpdYMY6XHuUgCUQh44xdWL6.wpX25enuE6bpQcPx2",
        "1223-8901-3009-7820"
    );
    INSERT INTO users VALUES
    (
        "ryan7ven",
        "$2b$12$ieXN72pPwoV55G79ZCCpYOOiik70BdPUpTtTjRXm5G7Vm0SmJiToW",
        "8953-0201-2713-6347"
    );
    INSERT INTO users VALUES
    (
        "tomlain",
        "$2b$12$BhqvSyguu8o3JhOfa84yqOHC1A7VK.YSUGxSpOzKjyEyUVpmOLhz2",
        "4555-7002-8913-9732"
    );
    INSERT INTO users VALUES
    (
        "sam2mate",
        "$2b$12$pt5bhrmMn2bDgcDdC45C/OcbJjWC8rtljCnvC4WBcZFY1Gjf.RSYe",
        "1000-3425-9137-3880"
    );
    INSERT INTO users VALUES
    (
        "ironman22",
        "$2b$12$d1WiRB3hg3zGScSKSYmmzuhyA4dZ8CRCTAwnKg5NT24ohVCRkdDmi",
        "7272-9871-0100-3333"
    );
    INSERT INTO users VALUES
    (
        "admin",
        "$2b$12$2RHe1SGBhSC4f/ZWFqqPL.OPXCisHbZ36UVzTd.MJ/FuYggXr649i",
        "4539-0035-6342-4817"
    );
