# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 3000
      containers:
      - name: server
        image: eu.gcr.io/research-gcp-credits/shippingservice@sha256:d60808ff779bd24442ad5b4f282e5bceba46ef9c5ff19f0c4bc5b7898d14ebcc
        ports:
        - containerPort: 50051
        securityContext:
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 3000
          allowPrivilegeEscalation: false
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      - name: tcpdump
        image: corfr/tcpdump
        imagePullPolicy: Always
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: tcpdump-init
            mountPath: /home/root/
          - name: tcpdump-persistent-storage
            mountPath: /tmp
        command: ["/bin/sh", "-c"]
        args:
        - sh /home/root/start-tcpdump.sh shippingservice 900
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
      volumes:
        - name: tcpdump-init
          configMap:
            name: tcpdump-script-configmap
        - name: tcpdump-persistent-storage
          persistentVolumeClaim:
            claimName: shippingservice-tcpdump-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
