apiVersion: v1
kind: PersistentVolume
metadata:
  name: adservice-tcpdump-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/files/adservice"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adservice-tcpdump-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi