apiVersion: v1
kind: PersistentVolume
metadata:
  name: productdb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/products"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: productdb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi